### ISSUE TITLE
docker image missing

### ISSUE THREAD

**Issue by jaybauson** [ahab94/xerxes-II#2]
I tried the docker-compose file, image is missing, tried to build the Dockerfile and can't run either. Like it will run for a minute, and it will exit.

**Comment by ahab94** [comment]
Hi @jaybauson, apologies for the late response. 
One precondition to running the docker-compose is to have the image built inside the system. To build an image you will need to do `sudo docker build . -t xerxes` inside the root dir of xerxes-II. As soon as you have the image built, you will be able to use docker-compose.
